# runtime: nodejs10
# handlers:
# - url: /(.*\..+)$
#   static_files: build/\1
#   upload: build/(.*\..+)$
# - url: /.*
#   static_files: build/index.html
#   upload: build/index.html

# service: service4
runtime: nodejs
env: flex
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 10
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.9
resources:
  cpu: 2
  memory_gb: 4.6
  disk_size_gb: 10
network: 
  name: service4
  forwarded_ports:
    - 7003/tcp